### ISSUE TITLE
Using the .query() method - AND / OR error 

### ISSUE THREAD

**Issue by benjamin-jacobson** [learn-co-curriculum/dsc-using-sql-with-pandas-lab#1]
In the "Using the .query() method" section, the task is to "In the cell below, use the query() method to return a DataFrame that contains only female passengers of ages 15 and under."  

However, the solution is showing and OR where AND should be:

female_children_df = df.query("Sex == 'female' or Age <= 15") # should be AND
female_children_df.head()

**Comment by sumedh10** [comment]
Thanks for reporting, this is fixed.
