### ISSUE TITLE
In Solution branch: poor_male_survivors_df are all dead :-/

### ISSUE THREAD

**Issue by jmarkowi** [learn-co-curriculum/dsc-using-sql-with-pandas-lab#4]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

https://learning.flatironschool.com/courses/4243/assignments/133334?module_item_id=275984

## What should be changed?

In the "Solution" branch, at the end of the "Slicing DataFrames Using Conditional Logic" section, poor_male_survivors_df is made of poor men from the Titanic, but none of them actually survived (poor_male_survivors_df['Survived'] is 0s all the way down).

## Additional context

Original: poor_male_survivors_df = df[(df['Pclass'].isin(['2', '3'])) & (df['Sex'] == 'male')]
Should probably read: poor_male_survivors_df = df[(df['Pclass'].isin(['2', '3'])) & (df['Sex'] == 'male') & (df['Survived'] == 0)]

**Comment by jessepisel** [comment]
Thanks for opening this issue @jmarkowi :wave:. I have added the survival filter for the query in commit b127a56360b99939c644955cc123c799848f9e88.

I am closing this issue at this time.
